2018-11-12 22:13:51,441 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:13:51,922 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:13:51,922 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:13:51,922 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:13:51,922 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:13:51,941 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:13:51,956 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:19:03,967 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_images.py', reloading
2018-11-12 22:19:03,990 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:19:04,356 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:19:04,357 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:19:04,357 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:19:04,357 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:19:04,369 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:19:04,382 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:22:10,411 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_images.py', reloading
2018-11-12 22:22:10,481 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:22:10,942 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:22:10,943 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:22:10,944 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:22:10,944 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:22:10,969 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:22:11,000 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:23:54,717 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_images.py', reloading
2018-11-12 22:23:54,741 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:23:55,056 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:23:55,056 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:23:55,056 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:23:55,056 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:23:55,070 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:23:55,088 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:25:42,819 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_images.py', reloading
2018-11-12 22:25:42,851 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:25:43,422 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:25:43,422 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:25:43,422 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:25:43,422 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:25:43,433 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:25:43,446 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:26:36,377 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_images.py', reloading
2018-11-12 22:26:36,407 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:26:37,293 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:26:37,293 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:26:37,293 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:26:37,293 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:26:37,371 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:26:37,410 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:31:21,319 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_images.py', reloading
2018-11-12 22:31:21,351 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:31:21,706 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:31:21,706 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:31:21,706 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:31:21,706 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:31:21,718 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:31:21,734 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:33:14,895 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_preview.py', reloading
2018-11-12 22:33:14,963 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:33:15,266 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:33:15,266 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:33:15,266 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:33:15,266 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:33:15,276 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:33:15,290 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:33:34,792 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_images.py', reloading
2018-11-12 22:33:34,818 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:33:35,146 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:33:35,146 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:33:35,146 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:33:35,146 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:33:35,159 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:33:35,175 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:46:48,560 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_fs.py', reloading
2018-11-12 22:46:48,586 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:46:48,946 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:46:48,946 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:46:48,946 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:46:48,947 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:46:48,961 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:46:48,976 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:49:16,440 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_fs.py', reloading
2018-11-12 22:49:16,470 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:49:16,732 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:49:16,732 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:49:16,732 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:49:16,732 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:49:16,743 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:49:16,758 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:50:13,806 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_fs.py', reloading
2018-11-12 22:50:13,828 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:50:14,112 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:50:14,112 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:50:14,112 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:50:14,112 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:50:14,122 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:50:14,135 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:50:35,504 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_fs.py', reloading
2018-11-12 22:50:35,533 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:50:35,791 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:50:35,791 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:50:35,791 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:50:35,791 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:50:35,801 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:50:35,813 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:50:51,082 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_fs.py', reloading
2018-11-12 22:50:51,136 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:50:51,861 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:50:51,862 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:50:51,862 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:50:51,862 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:50:51,891 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:50:51,927 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:51:17,457 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_fs.py', reloading
2018-11-12 22:51:17,512 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:51:17,864 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:51:17,864 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:51:17,864 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:51:17,864 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:51:17,876 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:51:17,891 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:54:45,380 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_preview.py', reloading
2018-11-12 22:54:45,404 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:54:45,692 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:54:45,692 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:54:45,692 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:54:45,692 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:54:45,703 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:54:45,717 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:58:19,328 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_cache.py', reloading
2018-11-12 22:58:19,352 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:58:19,762 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:58:19,763 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:58:19,763 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:58:19,763 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:58:19,776 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:58:19,792 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 22:58:29,027 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_preview.py', reloading
2018-11-12 22:58:29,053 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 22:58:29,498 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 22:58:29,498 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 22:58:29,499 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 22:58:29,499 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 22:58:29,517 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 22:58:29,533 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 23:00:32,619 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_cache.py', reloading
2018-11-12 23:00:32,660 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 23:00:33,020 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 23:00:33,021 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 23:00:33,025 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 23:00:33,025 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 23:00:33,065 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 23:00:33,083 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 23:02:03,744 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_cache.py', reloading
2018-11-12 23:02:03,768 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 23:02:04,129 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 23:02:04,129 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 23:02:04,129 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 23:02:04,129 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 23:02:04,140 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 23:02:04,154 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 23:03:16,358 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_cache.py', reloading
2018-11-12 23:03:16,383 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 23:03:16,692 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 23:03:16,692 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 23:03:16,693 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 23:03:16,693 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 23:03:16,703 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 23:03:16,727 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 23:03:19,823 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_cache.py', reloading
2018-11-12 23:03:19,872 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 23:03:20,152 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 23:03:20,152 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 23:03:20,152 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 23:03:20,152 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 23:03:20,162 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 23:03:20,175 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 23:04:09,985 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_cache.py', reloading
2018-11-12 23:04:10,007 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 23:04:10,271 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 23:04:10,272 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 23:04:10,272 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 23:04:10,272 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 23:04:10,282 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 23:04:10,297 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 23:07:14,301 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_cache.py', reloading
2018-11-12 23:07:14,324 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 23:07:14,628 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 23:07:14,628 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 23:07:14,628 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 23:07:14,628 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 23:07:14,638 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 23:07:14,668 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 23:08:12,686 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_cache.py', reloading
2018-11-12 23:08:12,724 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 23:08:13,004 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 23:08:13,004 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 23:08:13,005 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 23:08:13,006 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 23:08:13,044 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 23:08:13,059 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 23:13:28,097 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_cache.py', reloading
2018-11-12 23:13:28,121 - [INFO] werkzeug [_internal, line 88]:  * Restarting with stat
2018-11-12 23:13:28,462 - [INFO] __main__ [app_api, line 46]: ================================================================
2018-11-12 23:13:28,463 - [INFO] __main__ [app_api, line 47]: ================================================================
2018-11-12 23:13:28,463 - [INFO] __main__ [app_api, line 48]: ================================================================
2018-11-12 23:13:28,463 - [INFO] __main__ [app_api, line 49]: Initialising app
2018-11-12 23:13:28,472 - [WARNING] werkzeug [_internal, line 88]:  * Debugger is active!
2018-11-12 23:13:28,492 - [INFO] werkzeug [_internal, line 88]:  * Debugger PIN: 262-750-570
2018-11-12 23:14:15,254 - [INFO] werkzeug [_internal, line 88]:  * Detected change in '/Users/home/Google_Drive/_CODE/python.homemedia_api/api/core/utils_cache.py', reloading
